# Generated by Django 4.2.6 on 2023-12-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='created',
            new_name='created_at',
        ),
    ]
